# Generated by Django 2.2 on 2021-08-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='occupied',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
