# Generated by Django 2.2 on 2021-08-05 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('length', models.PositiveIntegerField()),
                ('occupied', models.BooleanField(default=False)),
                ('daily_charge', models.PositiveIntegerField()),
                ('weekly_charge', models.PositiveIntegerField()),
                ('monthly_charge', models.PositiveIntegerField()),
                ('access_code', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=20)),
                ('nok_fullname', models.CharField(blank=True, max_length=100)),
                ('nok_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nok_number', models.CharField(blank=True, max_length=100)),
                ('nok_relationship', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('address', models.CharField(max_length=200)),
                ('payment_mode', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=30)),
                ('total_cost', models.PositiveIntegerField(null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='mainapp.Profile')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='mainapp.Unit')),
            ],
        ),
    ]
