# Generated by Django 2.2 on 2021-08-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='access_code',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cost_currency',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_cost_currency',
        ),
    ]
