# Generated by Django 2.2 on 2021-08-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='size',
            field=models.CharField(choices=[('-----', '-----'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('X-large', 'X-large'), ('2X-large', '2X-large'), ('3X=large', '3X-large')], default='-----', max_length=100),
        ),
    ]
