# Generated by Django 2.2 on 2021-08-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='billing_Cycle',
            field=models.CharField(choices=[('-----', '-----'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='-----', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(choices=[('-----', '-----'), ('Mpesa', 'Mpesa'), ('Bank', 'Bank'), ('Cash', 'Cash')], default='-----', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
