# Generated by Django 2.2 on 2021-08-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210805_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='is_employee',
        ),
        migrations.AddField(
            model_name='usertype',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
