# Generated by Django 2.2 on 2021-08-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #('mainapp', '0002_auto_20210807_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pic',
        ),
    ]
