# Generated by Django 2.2 on 2021-08-19 07:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210817_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1627343010/neighborhood1_cj2fyx.jpg', max_length=255, verbose_name='images'),
        ),
    ]
