# Generated by Django 2.2 on 2021-08-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210805_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('client', 'client'), ('employee', 'employee')], max_length=100, null=True, verbose_name='User Type'),
        ),
    ]
