# Generated by Django 2.2 on 2021-08-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='profiles/default.jpg', upload_to='profiles/'),
        ),
    ]
