# Generated by Django 2.2 on 2021-08-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210806_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitname', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('employee', 'Employee')], max_length=100, null=True, verbose_name='User Type'),
        ),
    ]
