# Generated by Django 2.2 on 2021-08-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkoutRequestID', models.CharField(blank=True, max_length=100, null=True)),
                ('merchantRequestID', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('mpesaReceiptNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('transactionDate', models.DateTimeField(blank=True, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'verbose_name': 'CallBack Payment',
                'verbose_name_plural': 'CallBack Payments',
            },
        ),
    ]
