# Generated by Django 2.2 on 2021-08-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transactionDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
